server:
  port: 9446
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
wx:
  config:
    secret: 88bd7ac61d22821f71a00d8f7d781563
    appid: wxcd1cce2474cfc5cd
---
## 研发环境
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://106.12.180.252:3306/indigo_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

---
### 生产环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://106.12.180.252:3306/indigo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC