server:
  port: 9446
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
---
## 开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://106.12.180.252:3306/indigo_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

---
### 生产环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://106.12.180.252:3306/indigo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC